name: Azure Fullstack CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_frontend:
    runs-on: ubuntu-latest
    name: Build and Deploy Angular Frontend
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install Frontend Dependencies
        run: npm config set legacy-peer-deps true && npm install
        working-directory: ./frontend/angular-spotify

      - name: Build Angular App
        run: npx nx build angular-spotify --prod
        working-directory: ./frontend/angular-spotify

      - name: Deploy Frontend to Azure Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./frontend/angular-spotify" # Angular app root
          output_location: "./frontend/angular-spotify/dist/angular-spotify" # Angular build folder

  build_and_deploy_backend:
    runs-on: ubuntu-latest
    needs: build_and_deploy_frontend
    name: Build and Deploy .NET Backend
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore .NET dependencies
        run: dotnet restore ./backend/MusicService/MusicService.csproj

      - name: Build .NET project
        run: dotnet build ./backend/MusicService/MusicService.csproj --configuration Release --no-restore

      - name: Publish .NET project
        run: dotnet publish ./backend/MusicService/MusicService.csproj --configuration Release --output ./publish

      - name: Deploy Backend to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: musicservice-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
